version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly
 - package-ecosystem: "github-actions"
   directory: "/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-config/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-core/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-entity/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-inventory/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-macros/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-protocol/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-registry/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin-world/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "pumpkin/"
   schedule:
     interval: weekly
 - package-ecosystem: "cargo"
   directory: "fuzz/"
   schedule:
     interval: weekly
