name: CI

on:
  push:
#  schedule:
#    - cron: '55 9 * * 1'

permissions:
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/riscv64
          push: true
          sbom: true
          provenance: mode=max
          tags: |
            ghcr.io/knight1/pumpkin:latest
            ghcr.io/knight1/pumpkin:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=ghcr.io/knight1/pumpkin:buildcache
          cache-to: type=registry,ref=ghcr.io/knight1/pumpkin:buildcache,mode=max